# Session secret. To generate, open irb and run:
# require 'securerandom'; SecureRandom.hex(64)
session_secret: "replace_me"

# URL of postgres database (optional). Example:
# database_url_development: "postgres://postgres@localhost/sinatra_backbone_development"
database_url_development:
database_url_test:
